# Generated by Django 3.2 on 2021-04-12 16:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=200, verbose_name='Název laboratoře')),
            ],
            options={
                'ordering': ['nazev'],
            },
        ),
        migrations.CreateModel(
            name='Misto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zemepisna_sirka', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='Zeměpisná šířka')),
                ('zemepisna_delka', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Zeměpisná délka')),
                ('mesto', models.CharField(blank=True, max_length=250, null=True, verbose_name='Město odběrného místa')),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100, verbose_name='Křestní jméno')),
                ('prijmeni', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('datum_narozeni', models.DateField(help_text='Zadejte datum narození ve formátu <em>YYYY-MM - DD < / em >.', verbose_name='Datum narození')),
                ('rodne_cislo', models.PositiveIntegerField(help_text='Zadejte rodné číslo bez lomítka.', unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Rodné číslo')),
                ('cislo_op', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Číslo OP')),
                ('mesto', models.CharField(max_length=200, verbose_name='Město')),
                ('ulice', models.CharField(max_length=220, verbose_name='Ulice')),
                ('psc', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999)], verbose_name='PSČ')),
                ('tel_cislo', models.IntegerField(max_length=9, verbose_name='Telefonní číslo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail')),
            ],
            options={
                'ordering': ['prijmeni'],
            },
        ),
        migrations.CreateModel(
            name='Pojistovna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pojistovna', models.CharField(choices=[('111 - VZP', '111 - VZP'), ('201 - Vojenská ZP ČR', '201 - Vojenská ZP ČR'), ('205 - ČPZP', '205 - ČPZP'), ('207 - OBZP', '207 - OBZP'), ('209 - ZP Škoda', '209 - ZP Škoda'), ('211 - ZPMVČR', '211 - ZPMVČR'), ('213 - RBP', '213 - RBP')], default='111 - VZP', max_length=20, verbose_name='Zdravotní pojišťovna')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navsteva', models.DateTimeField(auto_now_add=True, verbose_name='Čas návštěvy')),
                ('vyhodnoceni', models.CharField(choices=[('pozitivní', 'pozitivní'), ('negativní', 'negativní')], max_length=9, verbose_name='Vyhodnocení testu')),
                ('poznamka', models.TextField(blank=True, null=True, verbose_name='Poznámka')),
                ('laborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtest.laborator')),
                ('misto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtest.misto')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtest.osoba')),
            ],
            options={
                'ordering': ['navsteva'],
            },
        ),
        migrations.CreateModel(
            name='Pojistenec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cislo_pojistence', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Číslo pojištěnce')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtest.osoba')),
                ('zp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtest.pojistovna')),
            ],
            options={
                'ordering': ['cislo_pojistence'],
            },
        ),
    ]
