# Generated by Django 3.2 on 2021-04-12 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='rodne_cislo',
            field=models.CharField(help_text='Zadejte rodné číslo bez lomítka.', max_length=10, unique=True, verbose_name='Rodné číslo'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='tel_cislo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Telefonní číslo'),
        ),
    ]
