# Generated by Django 3.2 on 2021-05-05 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidtest', '0002_auto_20210412_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='psc',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='PSČ'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='tel_cislo',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(111111111)], verbose_name='Telefonní číslo'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='ulice',
            field=models.CharField(max_length=220, verbose_name='Ulice včetně č. p.'),
        ),
        migrations.AlterField(
            model_name='test',
            name='laborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtest.laborator', verbose_name='Laboratoř'),
        ),
        migrations.AlterField(
            model_name='test',
            name='misto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtest.misto', verbose_name='Místo provedení testu'),
        ),
        migrations.AlterField(
            model_name='test',
            name='osoba',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtest.osoba', verbose_name='Osoba'),
        ),
    ]
