# Generated by Django 3.2 on 2021-05-08 17:54

import covidtest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtest', '0003_auto_20210505_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistenec',
            name='cislo_pojistence',
            field=models.CharField(max_length=10, validators=[covidtest.models.is_number], verbose_name='Číslo pojištěnce'),
        ),
    ]
