# Generated by Django 3.2 on 2021-06-17 19:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidtest', '0005_auto_20210508_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='cislo_op',
            field=models.PositiveIntegerField(help_text='Pokud se jedná o nezletilou osobu, která nevlastní OP, zadejte OP zák. zástupce', unique=True, validators=[django.core.validators.MaxValueValidator(999999999)], verbose_name='Číslo OP'),
        ),
        migrations.AlterField(
            model_name='osoba',
            name='datum_narozeni',
            field=models.DateField(help_text='Zadejte datum narození ve formátu <em>YYYY-MM - DD.</em>', verbose_name='Datum narození'),
        ),
        migrations.AlterField(
            model_name='pojistenec',
            name='osoba',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='covidtest.osoba'),
        ),
    ]
