# Generated by Django 3.2 on 2021-06-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtest', '0006_auto_20210617_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pojistovna',
            name='pojistovna',
            field=models.CharField(choices=[('111 - VZP', '111 - VZP'), ('201 - Vojenská ZP ČR', '201 - Vojenská ZP ČR'), ('205 - ČPZP', '205 - ČPZP'), ('207 - OBZP', '207 - OBZP'), ('209 - ZP Škoda', '209 - ZP Škoda'), ('211 - ZPMVČR', '211 - ZPMVČR'), ('213 - RBP', '213 - RBP')], default='111 - VZP', max_length=20, unique=True, verbose_name='Zdravotní pojišťovna'),
        ),
    ]
